version: "3.8"
services:
  tempfetcher:
    build:
      context: .
      dockerfile: dockerfiles/tempfetcher.dockerfile
    env_file:
      - ./env/tempfetcher.env
  
  mongodb:
    image: 'mongo'
    volumes: 
      - data:/data/db
    env_file:
      - ./env/mongo.env

  dash_app:
    build:
      context: .
      dockerfile: dockerfiles/dash_app.dockerfile
    env_file:
    - ./env/dash_app.env
    ports:
      - '8050:8050'
      - '8000:8000'


volumes:
  data:

